name: Cassandra Web CI/CD

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker-compose build
      - name: Tags
        run: |
          docker tag cassandraproject/web cassandraproject/web:${{ github.sha }}
          docker tag cassandraproject/web cassandraproject/web:bobtest
      - name: Push
        run: |
          docker push cassandraproject/web:${{ github.sha }}
          docker push cassandraproject/web:bobtest
