name: Cassandra Web CI/CD

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - name: Docker login
      #   run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker-compose build
      # - name: Tags
      #   run: |
      #     docker tag cassandraproject/web cassandraproject/web:${{ github.ref }}
      # - name: Push Branch Tag
      #   run: |
      #     docker push cassandraproject/web:${{ github.ref }}
      # - name: Push Latest Tag
      #   if: github.ref == 'refs/heads/master'
      #   run: |
      #     docker push cassandraproject/web:latest
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: cassandraproject/web
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./php/Dockerfile
